server:
  port: 9090
  servlet:
    context-path: /course

spring:
  application:
    name: msvc-course
  datasource:
    url: jdbc:mysql://localhost:3306/coursesDb
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/