server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: 'http://localhost:8090'
          predicates:
            - Path=/student/api/student/**
        - id: courses
          uri: 'http://localhost:9090'
          predicates:
            - Path=/course/api/course/**
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: root
    password: 160004130
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: drop-and-create
    database-platform: org.hibernate.dialect.OracleDialect
    database: oracle
  security:
    user:
      name: admin
      password: 1234

logging:
  level:
    org.springframework.security: DEBUG

eureka:
  client:
    register-with-eureka: false