server:
  port: 8090
  servlet:
    context-path: /student

spring:
  application:
    name: msvc-student
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=studentBd;encrypt=true;trustServerCertificate=true
    username: sa
    password: 160004130
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.SQLServerDialect
    database: SQL_SERVER
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
